/**
 * Copies contract ABIs (from `forge build` output) and deployment addresses (from deployments/*.json)
 * into the Next.js app as typed `as const` modules, so viem/wagmi infer function + event types.
 *
 *   npm run export-abi
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "../src/lib/chain");
const names = ["IdentityRegistry", "ValidatorStaking", "ValidationRegistry", "Escrow", "ChallengeMarket", "ReputationRegistry"];

mkdirSync(outDir, { recursive: true });

// The Envio indexer (../indexer) reads plain ABI JSON files.
const indexerAbiDir = resolve(root, "../indexer/abis");
mkdirSync(indexerAbiDir, { recursive: true });

let abiTs = "// Generated by contracts/scripts/export-abi.ts — do not edit.\n\n";
for (const name of names) {
  const artifact = JSON.parse(readFileSync(join(root, "out", `${name}.sol`, `${name}.json`), "utf8"));
  abiTs += `export const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
  writeFileSync(join(indexerAbiDir, `${name}.json`), JSON.stringify(artifact.abi, null, 2) + "\n");
}
writeFileSync(join(outDir, "abi.ts"), abiTs);

// The web app runs on Monad testnet only, so only that deployment is exported to it.
const MONAD_TESTNET = 10143;
const deployments: Record<string, unknown> = {};
const depFile = join(root, "deployments", `${MONAD_TESTNET}.json`);
if (existsSync(depFile)) deployments[String(MONAD_TESTNET)] = JSON.parse(readFileSync(depFile, "utf8"));
writeFileSync(
  join(outDir, "deployments.ts"),
  `// Generated by contracts/scripts/export-abi.ts — do not edit.\n\n` +
    `export interface Deployment {\n  chainId: number;\n  startBlock: number;\n  deployer: \`0x\${string}\`;\n` +
    names.map((n) => `  ${n}: \`0x\${string}\`;`).join("\n") +
    `\n}\n\nexport const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n`,
);

console.log(
  `Wrote ABIs for ${names.length} contracts to ${outDir}` +
    (deployments[String(MONAD_TESTNET)] ? " with the Monad testnet deployment" : " (no Monad testnet deployment yet)"),
);
