import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Solidity workspace + agents have their own tooling.
    "contracts/**",
    "indexer/**",
    "cre/**",
    // Generated by contracts/scripts/export-abi.ts.
    "src/lib/chain/abi.ts",
    "src/lib/chain/deployments.ts",
  ]),
]);

export default eslintConfig;
